In [1]:
%load_ext autoreload
%autoreload 2

# Make test datasets for processing multisearch results

In [2]:
import pandas as pd

In [3]:
def _make_multisearch_csv(
    moltype,
    ksize,
    pipeline_outdir="s3://seanome-kmerseek/scope-benchmark/pipeline-outputs/2024-10-08__protein_k5-20",
    query="astral-scopedom-seqres-gd-sel-gs-bib-40-2.08.part_001.fa",
    against="astral-scopedom-seqres-gd-sel-gs-bib-40-2.08.part_001.fa",
):
    basename = f"{query}--in--{against}.{moltype}.{ksize}.multisearch.csv"
    csv = f"{pipeline_outdir}/sourmash/multisearch/{basename}"
    return csv


csv = _make_multisearch_csv("protein", 10)
csv

's3://seanome-kmerseek/scope-benchmark/pipeline-outputs/2024-10-08__protein_k5-20/sourmash/multisearch/astral-scopedom-seqres-gd-sel-gs-bib-40-2.08.part_001.fa--in--astral-scopedom-seqres-gd-sel-gs-bib-40-2.08.part_001.fa.protein.10.multisearch.csv'

In [19]:
multisearch = pd.read_csv(csv)
print(multisearch.shape)
multisearch.head()

(16725, 13)

,query_name,query_md5,match_name,match_md5,containment,max_containment,jaccard,intersect_hashes,prob_overlap,prob_overlap_adjusted,containment_adjusted,containment_adjusted_log10,tf_idf_score
0,d4j42a_ a.25.3.0 (A:) automated matches {Bacil...,7b293810423d129c1c6e932adbacc00d,d4j42a_ a.25.3.0 (A:) automated matches {Bacil...,7b293810423d129c1c6e932adbacc00d,1.0,1.0,1.000000,71.0,9.971266e-12,0.002297,435.389380,2.638878,9.934455
1,d3gcea_ b.33.1.0 (A:) automated matches {Nocar...,0be9ab661c03aab8b73841b2727198c4,d3gcea_ b.33.1.0 (A:) automated matches {Nocar...,0be9ab661c03aab8b73841b2727198c4,1.0,1.0,1.000000,95.0,1.334183e-11,0.003073,325.396274,2.512413,9.934455
2,d1dlwa_ a.1.1.1 (A:) Protozoan/bacterial hemog...,d7880d90a67ec70b21f3f15b43a8051d,d1dlwa_ a.1.1.1 (A:) Protozoan/bacterial hemog...,d7880d90a67ec70b21f3f15b43a8051d,1.0,1.0,1.000000,107.0,1.502712e-11,0.003461,288.903234,2.460752,9.934455
3,d3tewa2 b.179.1.1 (A:15-225) PA14 {Bacillus an...,1b36b1ba7e30ace7d13c10010c4314b8,d3tewa2 b.179.1.1 (A:15-225) PA14 {Bacillus an...,1b36b1ba7e30ace7d13c10010c4314b8,1.0,1.0,1.000000,202.0,4.648576e-11,0.010708,93.391680,1.970308,9.848143
4,d3j9ca1 b.179.1.1 (A:174-225) PA14 {Bacillus a...,95b4a9065fa94dbfba9f10f72beb90df,d3tewa2 b.179.1.1 (A:15-225) PA14 {Bacillus an...,1b36b1ba7e30ace7d13c10010c4314b8,1.0,1.0,0.212871,43.0,2.415574e-11,0.005564,179.724686,2.254608,9.528990

In [20]:
import process_scop_sourmash_multisearch

In [21]:
parser = process_scop_sourmash_multisearch.MultisearchParser(
    pipeline_outdir="s3://seanome-kmerseek/scope-benchmark/pipeline-outputs/2024-10-08__protein_k5-20",
    moltype="protein",
    ksize=10,
    analysis_outdir="s3://seanome-kmerseek/scope-benchmark/pipeline-outputs/protein/",
)

multisearch_parsed = parser.process_multisearch_scop_results()
print(multisearch_parsed.shape)
multisearch_parsed.head()

(832, 31)

,query_name,query_md5,match_name,match_md5,containment,max_containment,jaccard,intersect_hashes,prob_overlap,prob_overlap_adjusted,...,match_scop_lineage,match_scop_lineage_fixed,match_family,match_superfamily,match_fold,match_class,same_family,same_superfamily,same_fold,same_class
4,d3j9ca1 b.179.1.1 (A:174-225) PA14 {Bacillus a...,95b4a9065fa94dbfba9f10f72beb90df,d3tewa2 b.179.1.1 (A:15-225) PA14 {Bacillus an...,1b36b1ba7e30ace7d13c10010c4314b8,1.000000,1.000000,0.212871,43.0,2.415574e-11,0.005564,...,b.179.1.1,b.179.1.1,b.179.1.1,b.179.1,b.179,b,True,True,True,True
8,d3tewa2 b.179.1.1 (A:15-225) PA14 {Bacillus an...,1b36b1ba7e30ace7d13c10010c4314b8,d3j9ca1 b.179.1.1 (A:174-225) PA14 {Bacillus a...,95b4a9065fa94dbfba9f10f72beb90df,0.212871,1.000000,0.212871,43.0,2.415574e-11,0.005564,...,b.179.1.1,b.179.1.1,b.179.1.1,b.179.1,b.179,b,True,True,True,True
33,d1g41a_ c.37.1.20 (A:) HslU {Haemophilus influ...,659c8a7d1ebcb45aa1a39e018ddf7a36,d1um8a_ c.37.1.20 (A:) ClpX {Helicobacter pylo...,e42fe6376a2d25504ba3d3e29a99cfe4,0.004608,0.005634,0.002541,2.0,1.123523e-12,0.000259,...,c.37.1.20,c.37.1.20,c.37.1.20,c.37.1,c.37,c,True,True,True,True
41,d1njfa_ c.37.1.20 (A:) delta prime subunit of ...,ad01a75de2d1b1f594407d518b11918e,d1a5ta2 c.37.1.20 (A:1-207) delta prime subuni...,0c58d05ea38cabc65451cb463b278c60,0.008696,0.010101,0.004695,2.0,1.123523e-12,0.000259,...,c.37.1.20,c.37.1.20,c.37.1.20,c.37.1,c.37,c,True,True,True,True
48,d1a5ta2 c.37.1.20 (A:1-207) delta prime subuni...,0c58d05ea38cabc65451cb463b278c60,d1njfa_ c.37.1.20 (A:) delta prime subunit of ...,ad01a75de2d1b1f594407d518b11918e,0.010101,0.010101,0.004695,2.0,1.123523e-12,0.000259,...,c.37.1.20,c.37.1.20,c.37.1.20,c.37.1,c.37,c,True,True,True,True

In [24]:
multisearch_parsed_class_a = multisearch_parsed.query('query_class == "a"')
multisearch_parsed_class_a

,query_name,query_md5,match_name,match_md5,containment,max_containment,jaccard,intersect_hashes,prob_overlap,prob_overlap_adjusted,...,match_scop_lineage,match_scop_lineage_fixed,match_family,match_superfamily,match_fold,match_class,same_family,same_superfamily,same_fold,same_class
61,d6vkja2 a.114.1.0 (A:282-309) automated matche...,c6451fe1bc851aa108191e721a6e9db6,d1f5na1 a.114.1.1 (A:284-583) Interferon-induc...,831d0eb6474457220a852f996567485a,0.789474,0.789474,0.050847,15.0,8.426422e-12,0.001941,...,a.114.1.1,a.114.1.1,a.114.1.1,a.114.1,a.114,a,False,True,True,True
65,d1f5na1 a.114.1.1 (A:284-583) Interferon-induc...,831d0eb6474457220a852f996567485a,d6vkja2 a.114.1.0 (A:282-309) automated matche...,c6451fe1bc851aa108191e721a6e9db6,0.051546,0.789474,0.050847,15.0,8.426422e-12,0.001941,...,a.114.1.0,a.114.1.0,a.114.1.0,a.114.1,a.114,a,False,True,True,True
336,d2xzga2 a.118.1.0 (A:331-357) automated matche...,a3bd28ef9fe36b907de5fd7fe350de9f,d1bpoa1 a.118.1.4 (A:331-487) Clathrin heavy-c...,622c5a957de65e5f75d8ecc66ed3c3f0,1.000000,1.000000,0.121622,18.0,1.011171e-11,0.002329,...,a.118.1.4,a.118.1.4,a.118.1.4,a.118.1,a.118,a,False,True,True,True
744,d1bpoa1 a.118.1.4 (A:331-487) Clathrin heavy-c...,622c5a957de65e5f75d8ecc66ed3c3f0,d2xzga2 a.118.1.0 (A:331-357) automated matche...,a3bd28ef9fe36b907de5fd7fe350de9f,0.121622,1.000000,0.121622,18.0,1.011171e-11,0.002329,...,a.118.1.0,a.118.1.0,a.118.1.0,a.118.1,a.118,a,False,True,True,True
884,d4j19a_ a.4.1.1 (A:) automated matches {Human ...,38e0fa713c78f2017b47e86e7a9fecab,d1lfba_ a.4.1.1 (A:) Hepatocyte nuclear factor...,6abe1b786ff8ff3fb01185d68b058868,0.029412,0.029412,0.014815,2.0,1.123523e-12,0.000259,...,a.4.1.1,a.4.1.1,a.4.1.1,a.4.1,a.4,a,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5802,d4yt3a_ a.104.1.0 (A:) automated matches {Baci...,25c00c4ec61a454a6238d59d756989a2,d2jjna_ a.104.1.0 (A:) automated matches {Sacc...,f7532bfb95d4f207893d3f85bc0218a7,0.007538,0.007772,0.003841,3.0,1.390360e-11,0.003203,...,a.104.1.0,a.104.1.0,a.104.1.0,a.104.1,a.104,a,True,True,True,True
5803,d4rm4a_ a.104.1.0 (A:) automated matches {Baci...,b6869112d503f5ec1e203240ea625287,d2jjna_ a.104.1.0 (A:) automated matches {Sacc...,f7532bfb95d4f207893d3f85bc0218a7,0.008197,0.008197,0.004005,3.0,1.390360e-11,0.003203,...,a.104.1.0,a.104.1.0,a.104.1.0,a.104.1,a.104,a,True,True,True,True
5804,d4yzra_ a.104.1.0 (A:) automated matches {Baci...,a214be8bc503fc611639fd8f7e9ef357,d2jjna_ a.104.1.0 (A:) automated matches {Sacc...,f7532bfb95d4f207893d3f85bc0218a7,0.007653,0.007772,0.003871,3.0,1.390360e-11,0.003203,...,a.104.1.0,a.104.1.0,a.104.1.0,a.104.1,a.104,a,True,True,True,True
5805,d3r9ba_ a.104.1.0 (A:) automated matches {Myco...,789872406404d87576b0898a5df3150c,d2jjna_ a.104.1.0 (A:) automated matches {Sacc...,f7532bfb95d4f207893d3f85bc0218a7,0.007673,0.007772,0.003876,3.0,1.390360e-11,0.003203,...,a.104.1.0,a.104.1.0,a.104.1.0,a.104.1,a.104,a,True,True,True,True
5864,d3a4ga_ a.104.1.0 (A:) automated matches {Pseu...,929d2516594b5d5e193fa503a2b07b20,d2zbxa1 a.104.1.0 (A:8-406) automated matches ...,c5de637919960308717ad69e70072188,0.007772,0.007772,0.003881,3.0,2.387486e-12,0.000550,...,a.104.1.0,a.104.1.0,a.104.1.0,a.104.1,a.104,a,True,True,True,True

In [28]:
multisearch_parsed_class_a.to_csv(
    "multisearch_results_processed_filtered.csv", index=False
)

### Remove unused categories for testing

In [56]:
from typing import get_args

from scop_constants import SCOP_LINEAGES

In [58]:
lineages = get_args(SCOP_LINEAGES)

In [ ]:
multisearch_parsed_class_a.query_superfamily.cat.remove_unused_categories()

In [81]:
query_match = "query", "match"

for lineage in lineages:
    for qm in query_match:
        col = f"{qm}_{lineage}"
        multisearch_parsed_class_a[col] = multisearch_parsed_class_a[
            col
        ].cat.remove_unused_categories()
        print(multisearch_parsed_class_a[col].cat.categories)

Index(['a.102.1.0', 'a.102.1.2', 'a.102.1.3', 'a.102.2.1', 'a.103.1.0',
       'a.103.1.1', 'a.104.1.0', 'a.104.1.1', 'a.114.1.0', 'a.114.1.1',
       'a.118.1.0', 'a.118.1.4', 'a.118.8.0', 'a.123.1.0', 'a.123.1.1',
       'a.128.1.0', 'a.128.1.1', 'a.128.1.4', 'a.132.1.1', 'a.177.1.0',
       'a.177.1.1', 'a.208.1.0', 'a.208.1.1', 'a.211.1.0', 'a.211.1.1',
       'a.211.1.2', 'a.216.1.1', 'a.268.1.1', 'a.298.1.1', 'a.39.1.0',
       'a.39.1.5', 'a.4.1.1', 'a.4.5.0', 'a.40.1.1', 'a.5.2.1', 'a.7.8.1'],
      dtype='object')
Index(['a.102.1.0', 'a.102.1.2', 'a.102.1.3', 'a.102.2.1', 'a.103.1.0',
       'a.103.1.1', 'a.104.1.0', 'a.104.1.1', 'a.114.1.0', 'a.114.1.1',
       'a.118.1.0', 'a.118.1.4', 'a.118.8.0', 'a.123.1.0', 'a.123.1.1',
       'a.128.1.0', 'a.128.1.1', 'a.128.1.4', 'a.132.1.1', 'a.177.1.0',
       'a.177.1.1', 'a.208.1.0', 'a.208.1.1', 'a.211.1.0', 'a.211.1.1',
       'a.211.1.2', 'a.216.1.1', 'a.268.1.1', 'a.298.1.1', 'a.39.1.0',
       'a.39.1.5', 'a.4.1.1', 'a.4.5.0', 'a.40.1.1', 'a.5.2.1', 'a.7.8.1'],
      dtype='object')
Index(['a.102.1', 'a.102.2', 'a.103.1', 'a.104.1', 'a.114.1', 'a.118.1',
       'a.118.8', 'a.123.1', 'a.128.1', 'a.132.1', 'a.177.1', 'a.208.1',
       'a.211.1', 'a.216.1', 'a.268.1', 'a.298.1', 'a.39.1', 'a.4.1', 'a.4.5',
       'a.40.1', 'a.5.2', 'a.7.8'],
      dtype='object')
Index(['a.102.1', 'a.102.2', 'a.103.1', 'a.104.1', 'a.114.1', 'a.118.1',
       'a.118.8', 'a.123.1', 'a.128.1', 'a.132.1', 'a.177.1', 'a.208.1',
       'a.211.1', 'a.216.1', 'a.268.1', 'a.298.1', 'a.39.1', 'a.4.1', 'a.4.5',
       'a.40.1', 'a.5.2', 'a.7.8'],
      dtype='object')
Index(['a.102', 'a.103', 'a.104', 'a.114', 'a.118', 'a.123', 'a.128', 'a.132',
       'a.177', 'a.208', 'a.211', 'a.216', 'a.268', 'a.298', 'a.39', 'a.4',
       'a.40', 'a.5', 'a.7'],
      dtype='object')
Index(['a.102', 'a.103', 'a.104', 'a.114', 'a.118', 'a.123', 'a.128', 'a.132',
       'a.177', 'a.208', 'a.211', 'a.216', 'a.268', 'a.298', 'a.39', 'a.4',
       'a.40', 'a.5', 'a.7'],
      dtype='object')
Index(['a'], dtype='object')
Index(['a'], dtype='object')

/tmp/ipykernel_44245/2558641480.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  multisearch_parsed_class_a[col] = multisearch_parsed_class_a[

In [82]:
pq = "test-data/process_scop_sourmash_multisearch/multisearch_output_multisearch_results_processed_filtered.pq"

multisearch_parsed_class_a.to_parquet(
    pq,
    index=False,
    engine="pyarrow",
)

In [83]:
df = pd.read_parquet(pq)
df["query_class"].cat.categories

Index(['a'], dtype='object')

In [37]:
bool_cols = multisearch_parsed_class_a.columns[
    multisearch_parsed_class_a.dtypes == bool
]
bool_cols

Index(['same_family', 'same_superfamily', 'same_fold', 'same_class'], dtype='object')

In [38]:
multisearch_parsed_class_a[bool_cols].sum()

same_family          90
same_superfamily    136
same_fold           136
same_class          136
dtype: int64

In [44]:
multisearch_parsed_class_a["query_fold"].value_counts().head().to_dict()

{'a.104': 42, 'a.128': 22, 'a.211': 22, 'a.102': 8, 'a.39': 6}

In [36]:
cat_cols = multisearch_parsed_class_a.columns[
    multisearch_parsed_class_a.dtypes == pd.Categorical
]
cat_cols

Index(['query_name', 'query_md5', 'match_name', 'match_md5', 'query_scop_id',
       'query_scop_lineage', 'query_scop_lineage_fixed', 'match_scop_id',
       'match_scop_lineage', 'match_scop_lineage_fixed'],
      dtype='object')

In [45]:
# multisearch_parsed_class_a[cat_cols].value_counts()

In [46]:
described = multisearch_parsed_class_a.describe()
described

,containment,max_containment,jaccard,intersect_hashes,prob_overlap,prob_overlap_adjusted,containment_adjusted,containment_adjusted_log10,tf_idf_score
count,136.000000,136.000000,136.000000,136.000000,1.360000e+02,136.000000,136.000000,136.000000,136.000000
mean,0.042158,0.062033,0.014771,4.823529,1.169166e-11,0.002693,33.009110,1.137800,0.391684
std,0.128523,0.176702,0.027301,4.883657,4.083553e-11,0.009406,63.697496,0.555420,1.220605
min,0.003984,0.004505,0.002119,2.000000,1.123523e-12,0.000259,2.099188,0.322051,0.037964
25%,0.007538,0.007668,0.003732,2.000000,1.685284e-12,0.000388,5.003356,0.699236,0.066887
50%,0.011070,0.012012,0.005464,3.000000,6.038936e-12,0.001391,15.487857,1.189983,0.101703
75%,0.024933,0.027738,0.010582,5.000000,1.056814e-11,0.002434,26.626416,1.425308,0.229930
max,1.000000,1.000000,0.169312,32.000000,3.421127e-10,0.078803,429.342305,2.632804,9.528990

In [47]:
described.

,containment,max_containment,jaccard,intersect_hashes,prob_overlap,prob_overlap_adjusted,containment_adjusted,containment_adjusted_log10,tf_idf_score
count,136.000000,136.000000,136.000000,136.000000,136.0,136.000000,136.000000,136.000000,136.000000
mean,0.042158,0.062033,0.014771,4.823529,0.0,0.002693,33.009110,1.137800,0.391684
std,0.128523,0.176702,0.027301,4.883657,0.0,0.009406,63.697496,0.555420,1.220605
min,0.003984,0.004504,0.002119,2.000000,0.0,0.000259,2.099188,0.322051,0.037964
25%,0.007538,0.007668,0.003732,2.000000,0.0,0.000388,5.003356,0.699236,0.066887
50%,0.011070,0.012012,0.005464,3.000000,0.0,0.001391,15.487857,1.189983,0.101703
75%,0.024933,0.027738,0.010582,5.000000,0.0,0.002434,26.626416,1.425308,0.229930
max,1.000000,1.000000,0.169312,32.000000,0.0,0.078803,429.342305,2.632804,9.528990

In [30]:
multisearch_parsed_class_a.describe().to_dict()

{'containment': {'count': 136.0,
  'mean': 0.04215796841748978,
  'std': 0.12852272928200278,
  'min': 0.0039840637450199,
  '25%': 0.007537688442211,
  '50%': 0.011070110701107,
  '75%': 0.024933274021352272,
  'max': 1.0},
 'max_containment': {'count': 136.0,
  'mean': 0.062033324676982665,
  'std': 0.1767017914569656,
  'min': 0.0045045045045045,
  '25%': 0.0076677410094472005,
  '50%': 0.0120117392883773,
  '75%': 0.027738180090282723,
  'max': 1.0},
 'jaccard': {'count': 136.0,
  'mean': 0.014771496820621947,
  'std': 0.02730088975416133,
  'min': 0.0021186440677966,
  '25%': 0.003731558417655075,
  '50%': 0.0054644990046449505,
  '75%': 0.010582109679352676,
  'max': 0.1693121693121693},
 'intersect_hashes': {'count': 136.0,
  'mean': 4.823529411764706,
  'std': 4.8836573315970755,
  'min': 2.0,
  '25%': 2.0,
  '50%': 3.0,
  '75%': 5.0,
  'max': 32.0},
 'prob_overlap': {'count': 136.0,
  'mean': 1.169166043665705e-11,
  'std': 4.0835527507349194e-11,
  'min': 1.1235229248439209e-12,
  '25%': 1.685284387265881e-12,
  '50%': 6.038935721036073e-12,
  '75%': 1.0568137511813127e-11,
  'max': 3.4211273061497387e-10},
 'prob_overlap_adjusted': {'count': 136.0,
  'mean': 0.0026930726031962576,
  'std': 0.009406109676458866,
  'min': 0.0002587937636705,
  '25%': 0.0003881906455057,
  '50%': 0.00139101647972895,
  '75%': 0.002434278839525725,
  'max': 0.078802701037672},
 'containment_adjusted': {'count': 136.0,
  'mean': 33.009109584148376,
  'std': 63.69749598926837,
  'min': 2.0991882376095785,
  '25%': 5.003356333287996,
  '50%': 15.487857388522809,
  '75%': 26.62641552345066,
  'max': 429.3423053755369},
 'containment_adjusted_log10': {'count': 136.0,
  'mean': 1.1378003435157253,
  'std': 0.5554198554925478,
  'min': 0.3220513842182578,
  '25%': 0.6992363000186442,
  '50%': 1.1899834922133699,
  '75%': 1.42530832535174,
  'max': 2.6328036839276723},
 'tf_idf_score': {'count': 136.0,
  'mean': 0.3916837194958378,
  'std': 1.2206046630283809,
  'min': 0.0379641035908197,
  '25%': 0.0668873632391725,
  '50%': 0.10170282199206745,
  '75%': 0.2299299384895597,
  'max': 9.528990001295746}}

## Subsample original input data

In [26]:
multisearch_class_a = multisearch.query(
    "query_name in @multisearch_parsed_class_a.query_name"
)
print(multisearch_class_a.shape)
multisearch_class_a.head()

(235, 13)

,query_name,query_md5,match_name,match_md5,containment,max_containment,jaccard,intersect_hashes,prob_overlap,prob_overlap_adjusted,containment_adjusted,containment_adjusted_log10,tf_idf_score
60,d1f5na1 a.114.1.1 (A:284-583) Interferon-induc...,831d0eb6474457220a852f996567485a,d1f5na1 a.114.1.1 (A:284-583) Interferon-induc...,831d0eb6474457220a852f996567485a,1.000000,1.000000,1.000000,291.0,4.718796e-11,0.010869,92.001923,1.963797,9.913555
61,d6vkja2 a.114.1.0 (A:282-309) automated matche...,c6451fe1bc851aa108191e721a6e9db6,d1f5na1 a.114.1.1 (A:284-583) Interferon-induc...,831d0eb6474457220a852f996567485a,0.789474,0.789474,0.050847,15.0,8.426422e-12,0.001941,406.745342,2.609323,7.522887
65,d1f5na1 a.114.1.1 (A:284-583) Interferon-induc...,831d0eb6474457220a852f996567485a,d6vkja2 a.114.1.0 (A:282-309) automated matche...,c6451fe1bc851aa108191e721a6e9db6,0.051546,0.789474,0.050847,15.0,8.426422e-12,0.001941,26.557256,1.424183,0.491185
66,d6vkja2 a.114.1.0 (A:282-309) automated matche...,c6451fe1bc851aa108191e721a6e9db6,d6vkja2 a.114.1.0 (A:282-309) automated matche...,c6451fe1bc851aa108191e721a6e9db6,1.000000,1.000000,1.000000,19.0,8.988183e-12,0.002070,483.010094,2.683956,9.614351
335,d1bpoa1 a.118.1.4 (A:331-487) Clathrin heavy-c...,622c5a957de65e5f75d8ecc66ed3c3f0,d1bpoa1 a.118.1.4 (A:331-487) Clathrin heavy-c...,622c5a957de65e5f75d8ecc66ed3c3f0,1.000000,1.000000,1.000000,148.0,2.836895e-11,0.006535,153.032901,2.184785,9.885142

In [18]:
# %debug

In [65]:
import os

In [66]:
os.path.split(
    "test-data/process_scop_sourmash_multisearch/sourmash/multisearch/astral-scopedom-seqres-gd-sel-gs-bib-40-2.08.part_001.fa--in--astral-scopedom-seqres-gd-sel-gs-bib-40-2.08.part_001.fa.protein.10.multisearch.csv"
)

('test-data/process_scop_sourmash_multisearch/sourmash/multisearch',
 'astral-scopedom-seqres-gd-sel-gs-bib-40-2.08.part_001.fa--in--astral-scopedom-seqres-gd-sel-gs-bib-40-2.08.part_001.fa.protein.10.multisearch.csv')

In [67]:
"test-data/process_scop_sourmash_multisearch/sourmash/multisearch/astral-scopedom-seqres-gd-sel-gs-bib-40-2.08.part_001.fa--in--astral-scopedom-seqres-gd-sel-gs-bib-40-2.08.part_001.fa.protein.10.multisearch.csv".split(
    "/"
)

['test-data',
 'process_scop_sourmash_multisearch',
 'sourmash',
 'multisearch',
 'astral-scopedom-seqres-gd-sel-gs-bib-40-2.08.part_001.fa--in--astral-scopedom-seqres-gd-sel-gs-bib-40-2.08.part_001.fa.protein.10.multisearch.csv']

In [69]:
csv = os.path.join(
    "test-data",
    "process_scop_sourmash_multisearch",
    "sourmash",
    "multisearch",
    "astral-scopedom-seqres-gd-sel-gs-bib-40-2.08.part_001.fa--in--astral-scopedom-seqres-gd-sel-gs-bib-40-2.08.part_001.fa.protein.10.multisearch.csv",
)

multisearch_class_a.to_csv(
    csv,
    index=False,
)